### ISSUE TITLE
Palette is not using the palette from the image

### ISSUE THREAD

**Issue by abathur8bit** [pfiscarelli/CoCo_Sprite_Compiler#3]
If you load a sprite sheet that is using 2 colors, but has a palette of a full 16, only the first few palette indexes will be used. If you then load another sheet with the same 16 palette colors, but it uses a different 2 colors, cocosc will still only show 3 colors and end up compiling using the same indexes. 

Apparently the old version of cocosc kept the palette intact (spoke with the Invisible man).

Sample sheets included.

![bbidle](https://github.com/user-attachments/assets/a4fa9285-5064-4fac-a8a1-48c80d1fe720)
![square](https://github.com/user-attachments/assets/8acbfb97-6a6f-481e-96df-a1d072dbc341)

**Comment by pfiscarelli** [comment]
This behavior was originally by design, where palette values on imported PNG files that did not have exactly 16-colors with an alpha channel, would be interpolated to create a new palette.

An option has been added to alpha release v0.1.9086.26496, where this behavior is now user-selectable in settings. The default behavior is to now truncate a 16-color palette for indexed PNG and BMP images (up to 256-color, 8bpp palettes).
